services:
  - type: web
    name: bad-posture-backend
    env: python
    region: oregon
    plan: free
    repo: https://github.com/ChaitanyaPimpare/bad-posture-app
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.12